import type { Metadata } from "next";
import { PublicHeader } from "@/components/public/PublicHeader";
import { PublicFooter } from "@/components/public/PublicFooter";

export const metadata: Metadata = { title: "Termos de Uso", description: "Condições de uso do site e dos conteúdos da Bruna Flores Nutri.", alternates: { canonical: "/termos" } };

export default function TermsPage() {
  const items = [["Finalidade do site", "O site apresenta os serviços, disponibiliza conteúdos educativos e permite o envio de uma pré-consulta. O envio do formulário não confirma contratação, diagnóstico, prescrição ou reserva automática de horário."], ["Conteúdo educativo", "Artigos e materiais têm caráter informativo e não substituem avaliação individual. Condutas nutricionais dependem do contexto clínico e devem ser definidas por profissional habilitado."], ["Uso responsável", "Não utilize o formulário para urgências ou emergências. As informações devem ser verdadeiras e enviadas pelo próprio titular ou por responsável legal autorizado."], ["Propriedade intelectual", "Textos, identidade visual, materiais e conteúdos são protegidos. É permitido compartilhar links; reprodução comercial ou alteração depende de autorização prévia."], ["Disponibilidade e mudanças", "O site pode receber correções, melhorias ou interrupções técnicas. Estes termos podem ser atualizados, mantendo a data da versão vigente visível."], ["Privacidade", "O tratamento de dados segue a Política de Privacidade. Informações de saúde e dados de crianças recebem proteção reforçada."]];
  return <main className="min-h-screen bg-[#FBF7F1] text-[#3A3028]"><PublicHeader /><section className="border-b border-[#EDE1D6] bg-[#FFFDFC] px-5 py-16 lg:px-8"><div className="mx-auto max-w-4xl"><p className="brand-kicker mb-4">Uso claro e responsável</p><h1 className="font-serif text-5xl font-semibold md:text-6xl">Termos de Uso</h1><p className="mt-5 text-[#75675E]">Versão vigente: 4 de agosto de 2026.</p></div></section><section className="px-5 py-14 lg:px-8"><div className="mx-auto max-w-4xl divide-y divide-[#EDE1D6]">{items.map(([title, body]) => <article key={title} className="py-8 first:pt-0"><h2 className="font-serif text-2xl font-semibold">{title}</h2><p className="mt-3 text-sm leading-7 text-[#75675E]">{body}</p></article>)}</div></section><PublicFooter /></main>;
}
