"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

export default function PortalAccountPage() {
  const router = useRouter(); const [currentPassword, setCurrentPassword] = useState(""); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [message, setMessage] = useState(""); const [submitting, setSubmitting] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setSubmitting(true); const response = await fetch("/api/portal/password/change", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ currentPassword, password, confirmPassword }) }); const data = await response.json().catch(() => ({})); if (!response.ok) { setMessage(data.message ?? "Não foi possível alterar a senha."); setSubmitting(false); return; } setMessage("Senha atualizada com sucesso."); setSubmitting(false); router.refresh(); }
  return <main className="min-h-screen bg-[#F7F0E8] px-5 py-12 text-[#3A3028]"><form onSubmit={submit} className="mx-auto max-w-md rounded-3xl bg-white p-7 shadow-sm"><a href="/portal" className="text-sm font-semibold text-[#607A56] hover:underline">← Voltar ao portal</a><h1 className="mt-5 font-serif text-3xl font-semibold">Minha conta</h1><p className="mt-2 text-sm text-[#75675E]">Altere sua senha. As outras sessões do portal serão encerradas.</p><label className="mt-6 block text-sm font-semibold" htmlFor="current-password">Senha atual</label><input id="current-password" type="password" autoComplete="current-password" required value={currentPassword} onChange={(e) => setCurrentPassword(e.target.value)} className="brand-input mt-2" /><label className="mt-4 block text-sm font-semibold" htmlFor="new-password">Nova senha</label><input id="new-password" type="password" autoComplete="new-password" required value={password} onChange={(e) => setPassword(e.target.value)} className="brand-input mt-2" /><label className="mt-4 block text-sm font-semibold" htmlFor="confirm-password">Confirmar nova senha</label><input id="confirm-password" type="password" autoComplete="new-password" required value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} className="brand-input mt-2" /><button disabled={submitting} className="brand-btn-primary mt-5 w-full justify-center">{submitting ? "Alterando senha..." : "Alterar senha"}</button>{message && <p className="mt-4 text-sm" role="status">{message}</p>}</form></main>;
}
