"use client";
import { useCallback, useEffect, useState } from "react";
type Item = { id: string; snapshot_title?: string; original_filename?: string; status: string; published_at: string | null };
export function PatientDeliverablesPanel({ patientId }: { patientId: string }) {
  const [orientations, setOrientations] = useState<Item[]>([]); const [files, setFiles] = useState<Item[]>([]); const [cards, setCards] = useState<Array<{ id: string; title: string }>>([]); const [cardId, setCardId] = useState(""); const [message, setMessage] = useState("");
  const load = useCallback(async () => { const [o, f, c] = await Promise.all([fetch(`/api/admin/clients/${patientId}/orientations`), fetch(`/api/admin/clients/${patientId}/files`), fetch("/api/admin/patient-education-cards")]); if (o.ok) setOrientations((await o.json()).items); if (f.ok) setFiles((await f.json()).items); if (c.ok) setCards((await c.json()).items); }, [patientId]);
  useEffect(() => { void load(); }, [load]);
  const update = async (url: string, body: unknown) => { const r = await fetch(url, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); setMessage(r.ok ? "Atualização salva." : "Não foi possível concluir a atualização."); if (r.ok) await load(); };
  const addOrientation = async () => { if (!cardId) return; const r = await fetch(`/api/admin/clients/${patientId}/orientations`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ education_card_id: cardId }) }); setMessage(r.ok ? "Orientação adicionada como rascunho. Publique quando revisar." : "Não foi possível adicionar a orientação."); if (r.ok) { setCardId(""); await load(); } };
  const upload = async (file: File | undefined) => { if (!file) return; const form = new FormData(); form.set("file", file); setMessage("Enviando arquivo..."); const r = await fetch(`/api/admin/clients/${patientId}/files`, { method: "POST", body: form }); setMessage(r.ok ? "Arquivo privado enviado. Publique quando revisar." : "Não foi possível enviar o arquivo. Confira tipo e tamanho."); if (r.ok) await load(); };
  return <section className="rounded-2xl border border-[#EDE1D6] bg-[#FFFDFC] p-5"><p className="brand-kicker">Entregas do portal</p><h3 className="mt-1 font-serif text-lg font-semibold text-[#3A3028]">Orientações e arquivos</h3><div className="mt-4 grid gap-5 lg:grid-cols-2"><div><label className="brand-label">Nova orientação</label><div className="flex gap-2"><select value={cardId} onChange={(e) => setCardId(e.target.value)} className="brand-input"><option value="">Selecione do catálogo</option>{cards.map((c) => <option key={c.id} value={c.id}>{c.title}</option>)}</select><button type="button" onClick={() => void addOrientation()} className="brand-btn-secondary">Adicionar</button></div><div className="mt-3 space-y-2">{orientations.map((i) => <div key={i.id} className="flex items-center justify-between gap-2 text-sm"><span>{i.snapshot_title} · {i.status}</span>{i.status !== "REVOKED" && <button type="button" className="text-[#607A56] underline" onClick={() => void update(`/api/admin/clients/${patientId}/orientations`, { id: i.id, status: i.status === "PUBLISHED" ? "REVOKED" : "PUBLISHED" })}>{i.status === "PUBLISHED" ? "Revogar" : "Publicar"}</button>}</div>)}</div></div><div><label className="brand-label">Adicionar arquivo</label><input aria-label="Adicionar arquivo ao portal" type="file" accept="application/pdf,image/jpeg,image/png,image/webp" className="block w-full text-sm" onChange={(e) => void upload(e.target.files?.[0])} /><div className="mt-3 space-y-2">{files.map((i) => <div key={i.id} className="flex items-center justify-between gap-2 text-sm"><span>{i.original_filename} · {i.status}</span>{i.status !== "REVOKED" && <button type="button" className="text-[#607A56] underline" onClick={() => void update(`/api/admin/clients/${patientId}/files`, { id: i.id, status: i.status === "PUBLISHED" ? "REVOKED" : "PUBLISHED" })}>{i.status === "PUBLISHED" ? "Revogar" : "Publicar"}</button>}</div>)}</div></div></div>{message && <p className="mt-4 text-sm text-[#607A56]" role="status">{message}</p>}</section>;
}
