"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { ChevronRight, Search, Star, X } from "lucide-react";
import type { MealPlanMealPayload, MealPlanItemPayload } from "@/lib/repositories/meal-plans";
import { useDialogKeyboard } from "@/hooks/use-dialog-keyboard";

type Tab = "items" | "meals" | "plans" | "templates";
type Food = { ref: { source: "TACO" | "CUSTOM" | "MANUFACTURER" | "USDA"; sourceId: string }; name: string; sourceLabel: string | null };
type Saved = { id: string; name: string; meal_structure: string; meal: MealPlanMealPayload; usage_count: number; updated_at: string };
type Plan = { id: string; title: string; status: string; updated_at: string; meals: MealPlanMealPayload[] };
type Template = { id: string; title: string; target_group: string };
const tabs: { id: Tab; label: string }[] = [{ id: "items", label: "Itens" }, { id: "meals", label: "Refeições" }, { id: "plans", label: "Planos" }, { id: "templates", label: "Modelos" }];
const count = (meal: MealPlanMealPayload) => meal.items.length + (meal.options ?? []).reduce((n, o) => n + o.items.length, 0) + (meal.choice_groups ?? []).reduce((n, g) => n + g.items.length, 0);
const date = (value: string) => { const d = new Date(value); return Number.isNaN(d.getTime()) ? null : new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "2-digit" }).format(d); };
const Empty = ({ children }: { children: React.ReactNode }) => <p className="rounded-xl border border-dashed border-[#EAD8C2] bg-[#FBF7F1]/60 px-4 py-8 text-center text-sm text-[#75675E]">{children}</p>;
const Skeleton = () => <div className="space-y-2" aria-label="Carregando biblioteca">{[1, 2, 3, 4].map((i) => <div key={i} className="h-[72px] animate-pulse rounded-xl border border-[#EDE1D6] bg-[#FBF7F1]" />)}</div>;

/** R6.5.6: camada visual R4; aplicação continua local e limpa snapshots existentes. */
export function ReuseLibraryDrawer({ clientId, currentPlanId, onInsertMeal, onClose }: { clientId: string; currentPlanId?: string | null; onInsertMeal: (meal: MealPlanMealPayload) => void; onClose: () => void }) {
  const [tab, setTab] = useState<Tab>("items"), [filter, setFilter] = useState<"recent" | "favorites">("recent"), [search, setSearch] = useState("");
  const [recent, setRecent] = useState<Food[] | null>(null), [favorites, setFavorites] = useState<Food[] | null>(null), [saved, setSaved] = useState<Saved[] | null>(null), [plans, setPlans] = useState<Plan[] | null>(null), [templates, setTemplates] = useState<Template[] | null>(null), [selected, setSelected] = useState(""), [templateMeals, setTemplateMeals] = useState<Record<string, MealPlanMealPayload[]>>({});
  const [loading, setLoading] = useState(false), [error, setError] = useState(false);
  const container = useRef<HTMLDivElement | null>(null), close = useRef<HTMLButtonElement | null>(null), tabButtons = useRef<Array<HTMLButtonElement | null>>([]);
  useDialogKeyboard(container, onClose, true);
  useEffect(() => { requestAnimationFrame(() => close.current?.focus()); }, []);
  async function load() { setLoading(true); setError(false); try {
    if (tab === "items" && (filter === "recent" ? recent : favorites) === null) { const r = await fetch(filter === "recent" ? "/api/admin/foods/recent" : "/api/admin/foods/favorites", { cache: "no-store" }); if (!r.ok) throw Error(); const v = (await r.json() as { items: Food[] }).items; filter === "recent" ? setRecent(v) : setFavorites(v); }
    if (tab === "meals" && saved === null) { const r = await fetch("/api/admin/saved-meals", { cache: "no-store" }); if (!r.ok) throw Error(); setSaved((await r.json() as { items: Saved[] }).items); }
    if (tab === "plans" && plans === null) { const r = await fetch(`/api/admin/clients/${clientId}/meal-plans`, { cache: "no-store" }); if (!r.ok) throw Error(); setPlans((await r.json() as Plan[]).filter((p) => p.id !== currentPlanId)); }
    if (tab === "templates" && templates === null) { const r = await fetch("/api/admin/protocol-templates?type=DIETA", { cache: "no-store" }); if (!r.ok) throw Error(); setTemplates((await r.json() as { items: Template[] }).items); }
  } catch { setError(true); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [tab, filter]); // eslint-disable-line react-hooks/exhaustive-deps
  const clean = (item: MealPlanItemPayload): MealPlanItemPayload => ({ ...item, food_name_snapshot: null, nutrition_snapshot: null, resolved_grams_snapshot: null, quantity_resolution_snapshot: null, quantity_locked: false, substitutions_locked: false });
  const cleanMeal = (meal: MealPlanMealPayload): MealPlanMealPayload => ({ ...meal, items: meal.items.map(clean), options: (meal.options ?? []).map((o) => ({ ...o, items: o.items.map(clean) })), choice_groups: (meal.choice_groups ?? []).map((g) => ({ ...g, items: g.items.map(clean) })) });
  const applyFood = (food: Food) => { onInsertMeal({ name: food.name, items: [{ food: food.name, quantity: "100", unit: "g", food_source: food.ref.source, food_ref_id: food.ref.sourceId }] }); onClose(); };
  const applySavedMeal = (meal: Saved) => { onInsertMeal(cleanMeal(meal.meal)); void fetch(`/api/admin/saved-meals/${meal.id}`, { method: "POST" }); onClose(); };
  async function favorite(food: Food, active: boolean) { const r = active ? await fetch(`/api/admin/foods/favorites?source=${food.ref.source}&refId=${encodeURIComponent(food.ref.sourceId)}`, { method: "DELETE" }) : await fetch("/api/admin/foods/favorites", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ source: food.ref.source, refId: food.ref.sourceId }) }); if (r.ok) setFavorites((all) => active ? (all ?? []).filter((f) => `${f.ref.source}:${f.ref.sourceId}` !== `${food.ref.source}:${food.ref.sourceId}`) : [food, ...(all ?? [])]); }
  async function applyTemplate(id: string) { try { let meals = templateMeals[id]; if (!meals) { const r = await fetch(`/api/admin/protocol-templates/${id}/meals`, { cache: "no-store" }); if (!r.ok) throw Error(); meals = (await r.json() as { meals: MealPlanMealPayload[] }).meals; setTemplateMeals((old) => ({ ...old, [id]: meals! })); } meals.forEach((meal) => onInsertMeal(cleanMeal(meal))); onClose(); } catch { setError(true); } }
  const q = search.trim().toLocaleLowerCase("pt-BR"), includes = (value: string) => !q || value.toLocaleLowerCase("pt-BR").includes(q), foodList = ((filter === "recent" ? recent : favorites) ?? []).filter((f) => includes(f.name)), savedList = (saved ?? []).filter((m) => includes(m.name)), planList = (plans ?? []).filter((p) => includes(p.title)), templateList = (templates ?? []).filter((t) => includes(t.title)), selectedPlan = (plans ?? []).find((p) => p.id === selected), favoriteKeys = useMemo(() => new Set((favorites ?? []).map((f) => `${f.ref.source}:${f.ref.sourceId}`)), [favorites]);
  const placeholder = tab === "items" ? "Buscar alimento..." : tab === "meals" ? "Buscar refeição salva..." : tab === "plans" ? "Buscar plano..." : "Buscar modelo...";
  return createPortal(<div role="dialog" aria-modal="true" aria-labelledby="reuse-title" className="fixed inset-0 z-50 flex items-end justify-center overflow-hidden bg-black/30 backdrop-blur-sm sm:items-center sm:px-4 sm:py-6"><section ref={container} className="flex h-[88dvh] w-full flex-col overflow-hidden rounded-t-2xl border border-[#EAD8C2] bg-[#FFFDFC] shadow-[0_-16px_60px_rgba(58,48,40,0.28)] sm:h-auto sm:max-h-[calc(100dvh-3rem)] sm:max-w-3xl sm:rounded-[1.25rem] sm:shadow-[0_28px_90px_rgba(58,48,40,0.24)]">
    <header className="flex shrink-0 items-start justify-between border-b border-[#EDE1D6] px-5 py-4"><div><p className="brand-kicker">Reutilizar no plano</p><h2 id="reuse-title" className="font-serif text-2xl font-semibold text-[#3A3028]">Biblioteca de reuso</h2></div><button ref={close} type="button" onClick={onClose} className="rounded-lg p-2 text-[#75675E] hover:bg-[#FBF7F1]" aria-label="Fechar biblioteca de reuso"><X className="h-5 w-5" /></button></header>
    <div className="shrink-0 border-b border-[#EDE1D6] px-4 py-3 sm:px-5"><label className="flex items-center gap-2 rounded-xl border border-[#EAD8C2] bg-white px-3 py-2 focus-within:ring-2 focus-within:ring-[#7F9A74]/35"><Search className="h-4 w-4 text-[#75675E]" /><input value={search} onChange={(e) => setSearch(e.target.value)} className="min-w-0 flex-1 bg-transparent text-sm outline-none" placeholder={placeholder} aria-label="Buscar na biblioteca" /></label><div role="tablist" aria-label="Seções da biblioteca" className="mt-3 grid grid-cols-4 gap-1 rounded-xl bg-[#FBF7F1] p-1">{tabs.map((t, i) => <button key={t.id} ref={(node) => { tabButtons.current[i] = node; }} type="button" role="tab" aria-selected={tab === t.id} onClick={() => setTab(t.id)} onKeyDown={(e) => { if (!/^Arrow(Left|Right)$/.test(e.key)) return; e.preventDefault(); const next = (i + (e.key === "ArrowRight" ? 1 : 3)) % 4; setTab(tabs[next].id); tabButtons.current[next]?.focus(); }} className={`min-h-9 rounded-lg text-xs font-semibold ${tab === t.id ? "bg-white text-[#3A3028] shadow-sm" : "text-[#75675E]"}`}>{t.label}</button>)}</div>{tab === "items" && <div className="mt-3 flex gap-2">{(["recent", "favorites"] as const).map((value) => <button key={value} type="button" aria-pressed={filter === value} onClick={() => setFilter(value)} className={`rounded-full border px-3 py-1.5 text-xs font-semibold ${filter === value ? "border-[#607A56] bg-[#EAF0E4] text-[#46623E]" : "border-[#EAD8C2] text-[#75675E]"}`}>{value === "recent" ? "Recentes" : "Favoritos"}</button>)}</div>}</div>
    <main role="tabpanel" className="min-h-0 flex-1 overflow-y-auto overscroll-contain p-4 sm:p-5">{loading ? <Skeleton /> : error ? <div className="rounded-xl border border-red-200 bg-red-50 p-4"><p className="text-sm font-semibold text-red-700">Não foi possível carregar a biblioteca.</p><button type="button" onClick={() => void load()} className="mt-2 text-xs font-semibold text-[#607A56] hover:underline">Tentar novamente</button></div> : <>
      {tab === "items" && (foodList.length ? <ul className="space-y-2">{foodList.map((food) => { const key = `${food.ref.source}:${food.ref.sourceId}`, active = favoriteKeys.has(key); return <li key={key} className="flex items-center gap-3 rounded-xl border border-[#EDE1D6] bg-white px-3 py-3"><button type="button" onClick={() => applyFood(food)} className="min-w-0 flex-1 text-left"><span className="block truncate text-sm font-semibold text-[#3A3028]">{food.name}</span><span className="block text-xs text-[#75675E]">{food.sourceLabel ?? "Catálogo"}</span></button><button type="button" onClick={() => void favorite(food, active)} className="rounded-lg p-2 text-[#8C6E52]" aria-label={active ? `Remover ${food.name} dos favoritos` : `Favoritar ${food.name}`}><Star className={`h-4 w-4 ${active ? "fill-[#D9A441] text-[#D9A441]" : ""}`} /></button><button type="button" onClick={() => applyFood(food)} className="brand-btn-secondary shrink-0 !px-3 !py-2 text-xs">Usar</button></li>; })}</ul> : <Empty>{filter === "recent" ? "Nenhum alimento recente." : "Nenhum favorito."}</Empty>)}
      {tab === "meals" && (savedList.length ? <ul className="space-y-2">{savedList.map((meal) => <li key={meal.id} className="flex items-center gap-3 rounded-xl border border-[#EDE1D6] bg-white px-3 py-3"><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-[#3A3028]">{meal.name}</p><p className="text-xs text-[#75675E]">{count(meal.meal)} alimentos · {meal.meal_structure === "SIMPLE" ? "Simples" : meal.meal_structure}</p>{date(meal.updated_at) && <p className="mt-1 text-[11px] text-[#8C6E52]">Último uso: {date(meal.updated_at)}</p>}</div><button type="button" onClick={() => applySavedMeal(meal)} aria-label={`Usar ${meal.name}`} className="brand-btn-primary shrink-0 !px-3 !py-2 text-xs">Usar</button></li>)}</ul> : <Empty>Nenhuma refeição salva.</Empty>)}
      {tab === "plans" && (planList.length ? <div className="space-y-2">{planList.map((plan) => <article key={plan.id} className={`rounded-xl border bg-white ${selected === plan.id ? "border-[#7F9A74]" : "border-[#EDE1D6]"}`}><button type="button" onClick={() => setSelected(plan.id)} className="flex w-full items-center gap-3 px-3 py-3 text-left"><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold text-[#3A3028]">{plan.title || `Plano de ${date(plan.updated_at) ?? "data indisponível"}`}</span><span className="block text-xs text-[#75675E]">{plan.meals.length} refeições · {plan.status}</span></span><ChevronRight className={`h-4 w-4 text-[#75675E] ${selected === plan.id ? "rotate-90" : ""}`} /></button>{selected === plan.id && <div className="border-t border-[#EDE1D6] bg-[#FBF7F1]/50 p-2">{selectedPlan?.meals.length ? selectedPlan.meals.map((meal, i) => <div key={`${meal.name}-${i}`} className="flex items-center gap-3 rounded-lg px-2 py-2"><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold text-[#3A3028]">{meal.name}</span><span className="text-xs text-[#75675E]">{count(meal)} alimentos</span></span><button type="button" onClick={() => { onInsertMeal(cleanMeal(meal)); onClose(); }} aria-label={`Adicionar ${meal.name}`} className="brand-btn-secondary shrink-0 !px-3 !py-2 text-xs">Adicionar</button></div>) : <p className="p-2 text-sm text-[#75675E]">Este plano não tem refeições.</p>}</div>}</article>)}</div> : <Empty>Nenhum outro plano deste paciente ainda.</Empty>)}
      {tab === "templates" && (templateList.length ? <ul className="space-y-2">{templateList.map((template) => <li key={template.id} className="flex items-center gap-3 rounded-xl border border-[#EDE1D6] bg-white px-3 py-3"><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-[#3A3028]">{template.title}</p><p className="text-xs text-[#75675E]">Modelo · {template.target_group}</p></div><button type="button" onClick={() => void applyTemplate(template.id)} className="brand-btn-primary shrink-0 !px-3 !py-2 text-xs">Usar modelo</button></li>)}</ul> : <Empty>Nenhum modelo disponível.</Empty>)}
    </>}</main>
  </section></div>, document.body);
}
