"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

export default function ForceChangePasswordPage() {
  const router = useRouter(); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { fetch("/api/portal/password/required", { cache: "no-store" }).then((r) => { if (!r.ok) router.replace("/portal"); else setLoading(false); }).catch(() => router.replace("/portal")); }, [router]);
  async function submit(event: React.FormEvent) { event.preventDefault(); setSubmitting(true); const response = await fetch("/api/portal/password/change", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ password, confirmPassword }) }); const data = await response.json().catch(() => ({})); if (response.ok) router.replace("/portal"); else { setMessage(data.message ?? "Não foi possível alterar a senha."); setSubmitting(false); } }
  if (loading) return <main className="min-h-screen bg-[#F7F0E8] p-8 text-center text-[#607A56]">Carregando…</main>;
  return <main className="min-h-screen bg-[#F7F0E8] px-5 py-12 text-[#3A3028]"><form onSubmit={submit} className="mx-auto max-w-md rounded-3xl bg-white p-7 shadow-sm"><p className="text-sm font-semibold text-[#607A56]">Bruna Flores Nutri</p><h1 className="mt-2 font-serif text-3xl font-semibold">Crie sua nova senha</h1><p className="mt-3 text-sm text-[#75675E]">Você entrou usando uma senha temporária. Antes de continuar, crie uma senha pessoal.</p><label className="mt-6 block text-sm font-semibold" htmlFor="password">Nova senha</label><input id="password" type="password" autoComplete="new-password" required value={password} onChange={(e) => setPassword(e.target.value)} className="brand-input mt-2" /><label className="mt-4 block text-sm font-semibold" htmlFor="confirm">Confirmar nova senha</label><input id="confirm" type="password" autoComplete="new-password" required value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} className="brand-input mt-2" /><button className="brand-btn-primary mt-5 w-full justify-center" disabled={submitting}>{submitting ? "Salvando..." : "Salvar nova senha"}</button>{message && <p className="mt-4 text-sm text-red-600" role="alert">{message}</p>}</form></main>;
}
