/**
 * FASE 5 (item 4) — queries naturais tais como uma nutricionista digitaria,
 * incluindo exatamente a lista dada no pedido, expandida com variações do
 * mesmo padrão (grão/preparo/corte) pros mesmos alimentos-base, nunca
 * inventando alimentos que não existem nas fontes reais.
 */
export const FASE5_NATURAL_QUERIES: string[] = [
  "arroz",
  "arroz branco",
  "arroz integral",
  "arroz integral cozido",
  "arroz branco cozido",
  "feijão",
  "feijão preto",
  "feijão preto cozido",
  "feijão carioca cozido",
  "ovo",
  "ovo cozido",
  "ovo mexido",
  "ovo frito",
  "clara de ovo",
  "gema de ovo",
  "frango",
  "peito de frango",
  "peito de frango grelhado",
  "frango grelhado",
  "coxa de frango",
  "frango assado",
  "banana",
  "banana prata",
  "banana nanica",
  "banana da terra",
  "mamão",
  "mamão papaya",
  "abacate",
  "abacate polpa",
  "leite integral",
  "leite desnatado",
  "leite semidesnatado",
  "milho",
  "milho cru",
  "milho cozido",
  "milho assado",
  "milho verde",
  "tilápia",
  "tilápia assada",
  "tilápia grelhada",
  "tilápia frita",
  "carne moída",
  "carne bovina",
  "patinho cozido",
  "alcatra grelhada",
  "batata",
  "batata cozida",
  "batata inglesa",
  "batata doce",
  "batata doce cozida",
  "mandioca cozida",
  "aipim",
  "pão francês",
  "pão de forma integral",
  "pão integral",
  "queijo minas",
  "queijo mussarela",
  "iogurte natural",
  "iogurte desnatado",
  "café com leite",
  "café sem açúcar",
  "brócolis",
  "brócolis cozido",
  "couve",
  "couve refogada",
  "alface",
  "tomate",
  "tomate cereja",
  "cenoura",
  "cenoura crua",
  "cenoura cozida",
  "abóbora cozida",
  "abobrinha",
  "beterraba cozida",
  "maçã",
  "laranja",
  "morango",
  "uva",
  "manga",
  "abacaxi",
  "melancia",
  "melão",
  "aveia",
  "aveia em flocos",
  "granola",
  "granola sem açúcar",
  "castanha do pará",
  "castanha de caju",
  "amendoim",
  "amendoim torrado",
  "azeite de oliva",
  "óleo de soja",
  "manteiga",
  "margarina",
  "açúcar refinado",
  "adoçante",
  "farinha de trigo",
  "farinha de mandioca",
  "macarrão cozido",
  "purê de batata",
  "sopa de legumes",
  "salada de frutas",
  "suco de laranja",
  "suco de uva integral",
  "água de coco",
  "peixe",
  "salmão",
  "salmão grelhado",
  "camarão",
  "atum em lata",
  "presunto",
  "peito de peru",
  "linguiça",
  "bacon",
  "chocolate meio amargo",
  "achocolatado",
  "achocolatado diet",
  "gelatina diet",
  "biscoito de água e sal",
  "biscoito recheado",
  "torrada integral",
  "tapioca",
  "cuscuz",
  "quinoa cozida",
  "lentilha cozida",
  "grão de bico cozido",
  "ervilha",
  "vagem cozida",
  "espinafre cozido",
  "rúcula",
  "pepino",
  "pimentão",
  "cebola",
  "alho",
  "salsa",
  "coentro",
];
